fullnameOverride: argo-cd

applicationSet:
  enabled: false

notifications:
  enabled: false

repoServer:
  image:
    repository: ghcr.io/shini4i/argocd
    tag: v2.7.6
    imagePullPolicy: IfNotPresent

  env:
    - name: HELM_PLUGINS
      value: "/home/argocd/.local/share/helm/plugins/"
