apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets/
    chart: sealed-secrets
    targetRevision: "2.16.1"
    helm:
      valuesObject:
        fullnameOverride: sealed-secrets
        # disable key rotation
        keyrenewperiod: "0"
        # update unsealing status, required for ArgoCD
        # to detect that SealedSecret was synced and unsealed successfully
        updateStatus: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
